# serverless.yml
service: reward-calendar

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: ${opt:stage, "development"}

  environment:

  iamRoleStatements:


functions:
  getData:
    handler: source/handlers.getData
    events:
      - http:
          path: getData
          method: get
          cors: true
  setDiffFeel:
    handler: source/handlers.setDiffFeel
    events:
      - http:
          path: setDiffFeel/{rowIndex}/feel/{feel}
          method: post
          cors: true
  setCompleted:
    handler: source/handlers.setCompleted
    events:
      - http:
          path: setCompleted/{rowIndex}/completed/{completed}
          method: post
          cors: true


plugins:
  - fullstack-serverless
  - ./public-policy-workaround.js

custom:
  fullstack:
    bucketName: deployed-bucket
    distributionFolder: ../client/dist
    indexDocument: index.html